# Generated by Django 3.1.1 on 2020-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='score',
            field=models.FloatField(default=6.2),
            preserve_default=False,
        ),
    ]
