# Generated by Django 3.1.1 on 2020-10-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_auto_20201029_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/images'),
            preserve_default=False,
        ),
    ]
